name: CI pipeline

on: [push]

jobs:
 sast_scan:
  name: Bandit Scan
  runs-on: ubuntu-latest

  steps:
  - name: Checkout code
    uses: actions/checkout@v2

  - name: Install python using pip
    uses: actions/setup-python@v2
    with:
      python-version: 3.8

  - name: Install Bandit 
    run: pip install bandit

  - name: Run Bandit scan
    # It states that only find the issues whose severity and confidence are medium and high 
    run: bandit -ll -ii -r . -f json -o bandit-report.json

  - name: Upload Artifacts
    uses: actions/upload-artifact@v4
    if: always()
    with:
      name: bandit-findings
      path: bandit-report.json

